### ISSUE TITLE
Logging error. One-time-password?

### ISSUE THREAD

**Issue by Sephiroth91** [goaaats/FFXIVQuickLauncher#10]
Hey,
I suspect that something is wrong with the one-time password.
I always try to log in with the launcher, but always I get the message: logging in failed. Check your logging in Information
I try it with the normal launcher everything is fine, but if I used yours I always get this error message.
I checked the password many times , I supect that there is a error by tranfering the password.

**Comment by goaaats** [comment]
Can you post a screenshot of the error message?

**Comment by Sephiroth91** [comment]
I write my password in a text document and copy&paste it in the ffxiv launcher. It works.
I paste it in your launcher and it does not work.
You are from Germany? Can we communicate in german? It is easier for me.
![launcher](https://user-images.githubusercontent.com/8442016/51323429-78602a80-1a68-11e9-89ac-cb64274411d4.jpeg)

**Comment by ThomasAunvik** [comment]
Im getting the same issue, though the path of the game is correct.

**Comment by goaaats** [comment]
Could not get local game version, or logging in failed?

**Comment by ThomasAunvik** [comment]
Login failed.

**Comment by goaaats** [comment]
Can you dm me on discord so I can give you a build to test with? It's meeboo#3048.

**Comment by goaaats** [comment]
Seems to be fixed in https://github.com/goaaats/FFXIVQuickLauncher/releases/tag/Build-15
