### ISSUE TITLE
[Feature Request] Synchronize Character Settings on client close

### ISSUE THREAD

**Issue by pigsflew** [goaaats/FFXIVQuickLauncher#100]
Basically, do what this script does on shutdown: https://gist.github.com/TomRichter/6b004eec543be27d0a55bcad124b24e7#file-xiv-ui-bat

* On client exit, check for FQL CharConf folder
* If not present, create folder at `%AppData%/FFXIVQuickLauncher/CharConf`
   * Copy Contents of latest-written Conf files to the FQL Char Config folder
* Iterate through FFXIV char settings folders
   * If any aren't junctioned to the FQL CharConf folder settings, junction them.

**Comment by goaaats** [comment]
Will do that, I don't think I'll use junctions, rather just overwrite the other characters with your main character - just so XIVLauncher won't do any permanent modifications, which are a pain to troubleshoot

**Comment by pigsflew** [comment]
Awesome! :D That makes sense. I'd still overwrite with the most recently changed files, not have to select a main or anything :)

**Comment by goaaats** [comment]
Implemented in https://github.com/goaaats/FFXIVQuickLauncher/commit/d1beaa27e4d8b4088f144d90c7c93f92b3b28bd8, please test if you can build it - if not, mind DMing me on Discord so I can give you one? at meeboo # 3048

**Comment by pigsflew** [comment]
Fixed with #101; all good now 😁
