### ISSUE TITLE
Launcher blocks volumouse app

### ISSUE THREAD

**Issue by dfscott** [goaaats/FFXIVQuickLauncher#105]
I run volumouse to adjust my volume.  It hooks the alt+mouse wheel combination to adjust the volume.  It works fine in-game with the stock launcher, but it doesn't with this launcher.  It's customizable to allow multiple key combinations, but nothing seems to work.  Is the launcher supposed to be capturing keys after FFXIV starts?

Edit: Just to follow-up, this doesn't appear to be a volmouse issues -- also tried it with Volume2 and it behaves the same way.

**Comment by dfscott** [comment]
Found a workaround (only for Volmouse) -- you have to run as Admin AND click the option to reload hooks every x millis.  Hopefully won't be a big performance hit but does allow me to use both now.

**Comment by Zyian** [comment]
Ensure that the launcher is not ran as admin (because this would cause the game to be launched as admin)

**Comment by goaaats** [comment]
I will add a message to not run the launcher as admin.

**Comment by Aida-Enna** [comment]
Fixed in https://github.com/goaaats/FFXIVQuickLauncher/commit/f9f77e6ab70c96837aa5f70638512539153be789
