### ISSUE TITLE
Launcher crashing after some windows updates.

### ISSUE THREAD

**Issue by woodshop2300** [goaaats/FFXIVQuickLauncher#106]
Just got back from installing some windows updates.
https://support.microsoft.com/en-us/help/4515384/windows-10-update-kb4515384
https://support.microsoft.com/en-us/help/4514359/sep-10-2019-kb4514359-cumulative-update-for-net-framework
https://support.microsoft.com/en-us/help/4516115/security-update-for-adobe-flash-player

Just before the reboot things were working great.
After the reboot, the app will just silently crash to desktop whenever i click the login button.

Event viewer is not really useful but says
```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: XIVLauncher.exe
P2: 3.6.0.0
P3: f707576b
P4: d3d9.dll
P5: 10.0.18362.329
P6: 1ac9a115
P7: c000001d
P8: 00000000000acd21
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E43.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_XIVLauncher.exe_23d7765b3a9f698544ef84d13f879f5603133dc_36767f5b_2248d45c-db52-45a4-a88e-8ed6fedb6820

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7b2030fb-4927-4cde-92a5-c6ab1a9c6ff7
Report Status: 100
Hashed bucket: 
Cab Guid: 0
```

[Report.zip](https://github.com/goaaats/FFXIVQuickLauncher/files/3726950/Report.zip)

grabbing b96a2cc6799746047a96d35771415acdda561226 and building it happens the same way. (start w/o debugging)
Start with debugging, and trying to run that way it won't even load instead you get.
```
The program '[5368] XIVLauncher.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.
```
 (in the output window).

In Release build i get the same thing, both with and without disabling "Just My Code"

**Comment by woodshop2300** [comment]
Removing kb4515384 appears to restore functionality.
Per VS2017 the instruction was in d3d. hum. more digging.

**Comment by goaaats** [comment]
Hmm, I'll try installing it - I assume this is just related to WPF again like the RivaTuner issues, so not much I can do :/
Would think that MS cares about their own UI frameworks enough to keep them working

**Comment by woodshop2300** [comment]
Probably, its not just your stuff thats for sure.
WinDbg (preview) 1.0.1910.03003 does the same thing, with the same workaround.
For now, I've hidden the update and things work well enough.

**Comment by goaaats** [comment]
Are you on insiders? Or is this normal windows updates? I don't think I've gotten it on Pro yet

**Comment by woodshop2300** [comment]
Not on insider, i did manually install the 1903 update instead of waiting for the rollout, i’m also on Ryzen but I don’t think that one is Ryzen specific.
I am on Pro as well.

**Comment by woodshop2300** [comment]
So this stuck back in with a windows roll up update which i can't uninstall.
Since you mentioned RivaTuner issue i decided to play, exiting RivaTuner does make it work again \o/.
Changing RivaTuner to "None" for application detection level makes it work \o/
And the best part, updating to the new RivaTuner 7.2.3 version makes it work with detection level Low \o/

**Comment by Squall-Leonhart** [comment]
just to explain what happened here,

Windows 10 starts applications in the background based on the state of the setting "Use sign-in info to auto finish after Update or Restart" this caused RTSS to be loaded DURING the replacement of DX runtimes causing the cache to be invalidated and reset, into a problematic state.

The changes in 7.2.3 invalidate the cache over several restarts following a detected change to the runtime library versions in order to avoid the situation occuring again.

**Comment by goaaats** [comment]
Thank you for confirming, closing as issue is resolved!
