### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by altissia86** [goaaats/FFXIVQuickLauncher#11]
1. Please add an option to save configuration at the same directory as the XIVLauncher.exe instead of current user profile. This will be useful for me, because I save my FFXIV in external SSD and play at home and office (ofcourse during break :D)

2. Please encrypt username and password inside config file.

**Comment by goaaats** [comment]
I just did 2 with https://github.com/goaaats/FFXIVQuickLauncher/commit/a3fcd21ee37de0ac665bc0e0472cd9cae628154c, should be a bit better now.

**Comment by Zinterax** [comment]
Suggestion for the addon system: Add an option to check if the process is already running before spawning a new process. For example if ACT is already running there probably is no reason to spawn a new copy of it.

**Comment by goaaats** [comment]
> Suggestion for the addon system: Add an option to check if the process is already running before spawning a new process. For example if ACT is already running there probably is no reason to spawn a new copy of it.

Done in https://github.com/goaaats/FFXIVQuickLauncher/commit/afbebc2b604b7c84dd4bf33e1b348b5a3d407f42

**Comment by Akurosia** [comment]
Is there a way of implementing the old functionality of Vekiens launcher, where the session was saved, so that OTP user only had to enter the OTP once every ~3 days?
Maybe as an option inside the settings?

**Comment by goaaats** [comment]
There's no "clean" way for me to confirm that a "unique id" still works, so not really. If it times out in set intervals, sure, but it doesn't seem like that to me.
Either way, I guess I can add it as an experimental option in the settings.

**Comment by Akurosia** [comment]
As i am still using vekiens old launcher, i can confirm that this still works + that everytime my account displays 4days left, the login is not longer working.

**Comment by Aida-Enna** [comment]
@Akurosia Does the experimental UUID cache work?

**Comment by Akurosia** [comment]
Usualy it works up to 3 days before you have to reenter the PW. 
Only exceptions are if a patch occure or if you log in from another place (also counts mogstation/lodestone)

I usually just make sure to be loged into lodestone at all times and reapply PW every 3 days (if you get 5006 on game start you have to manually reset it)

**Comment by Aida-Enna** [comment]
Sounds good, thanks for responding! \ o /
