### ISSUE TITLE
roulette info not showing?

### ISSUE THREAD

**Issue by mermaidens** [goaaats/FFXIVQuickLauncher#115]
ever since last patch, i'm no longer alerted as to what i get in roulettes. was the feature removed?

**Comment by Sephiroth018** [comment]
Same here, Duty Finder notifications are no longer working. Strange thing: When queueing up for a non roulette duty (e.g. dungeon "Hominster Switch"), the notification pops up immediately when queueing. So it seems like the feature is broken.

**Comment by goaaats** [comment]
This is fixed now for both roulettes and dungeons!
