### ISSUE TITLE
Launching default launcher whilst maintenance for patch update

### ISSUE THREAD

**Issue by ThomasAunvik** [goaaats/FFXIVQuickLauncher#123]
Related Issue: #118 

Should work the same when there is a new patch, but whilst there is a maintenance.

Not sure if it could be done to check if there is an update before there is a maintenance so you don't open the default launcher when there is no update but just maintenance.

**Comment by goaaats** [comment]
Done with https://github.com/goaaats/FFXIVQuickLauncher/commit/896fbfed949c28e89494d6421b94635da85338b0
