### ISSUE TITLE
Adding more than 1 account somehow replace 1st account password

### ISSUE THREAD

**Issue by seirralanzce** [goaaats/FFXIVQuickLauncher#125]
As title,

Step taken.

Was currently log on my main account.
1. Open QuickLauncher.
2. Create a main account Shortcut (didnt do this before because not needed for only 1 account).
3. Delete username and password, key in the 2nd account username and password, untick one-time, tick auto login, because 2nd account just free trial.
3. Login, then open quick launcher again, to set the character name and world in shortcut, then create short cut.
4. then exit both games.
5. try to login to main account, did not realize the password was somehow change at first till i get lock out for several minutes. Then realize when i key in the password, it was not the same length. 

Obviously i did not notice this at first because i thought it would auto set properly. but i did not proceed more as i decided to delete the 2nd account from QuickLauncher.

**Comment by Zyian** [comment]
Slimming down the reproducer:

1. Enter Username/Password hit login
2. Replace Username and password with second account
3. Hit Login
4. Use account switcher to change to primary account, password stays the same/overriden with 2nd account pw
