### ISSUE TITLE
Machinist Heated Clean Shot combo is broken

### ISSUE THREAD

**Issue by Sylt556** [goaaats/FFXIVQuickLauncher#126]
The combo starts with Heated Clean Shot instead of Heated Split Shot
The combo button doesn't change icon from Heated Clean Shot to Heated Split Shot and Heated Slug Shot
The combo resets to Heated Clean Shot if pressed after the GCD is over, even if only by a few tens of second (meaning while still within the combo window), this is especially damaging during overheat where GCDs are shorter.

**Comment by attickdoor** [comment]
It's intentional. You're accessing a debug/beta feature. This will be modified in the true release. MCH is a weird case heated and unheated shots are a bit strange, so I said screw it and just dumped it on the last possible button.
