### ISSUE TITLE
Chrome saying dangerous download build 19 

### ISSUE THREAD

**Issue by sslesar** [goaaats/FFXIVQuickLauncher#13]
![image](https://user-images.githubusercontent.com/25612653/54449146-57a11200-4745-11e9-8eaa-ecbfaf19f524.png)
Build 15 no dangerous to download.

**Comment by goaaats** [comment]
I can't really do anything about this - chrome will stop complaining about the file as soon as enough people download it.

I can assure though that no malicious code gets inserted into these releases and you can check using a .Net decompiler like dnSpy.
