### ISSUE TITLE
OTP macro broken in Android 10

### ISSUE THREAD

**Issue by jordguitar** [goaaats/FFXIVQuickLauncher#132]
Android 10 breaks the OTP macro due to a security change where applications can not access the clipboard automatically. The current macro is affected and it sends empty data and the launcher accepts the empty data and attempts to log in with it, which fails. The current error does not give any helpful information and I had to dump the OTP copy/send attempts to the user log in the application to see that no data was being sent.

Two changes should be made:

1) A code change where the OTP part of the launcher will not send a login attempt if there is no data for the OTP, with a error screen stating that no data was received.

2) A wiki change stating that Android 10 has broken the macro and there is currently no workaround unless the phone is rooted.

**Comment by Zyian** [comment]
Updated the wiki to reflect these changes

**Comment by jordguitar** [comment]
Workaround works just fine.

**Comment by Aida-Enna** [comment]
Confirmed - [The workaround in the wiki](https://github.com/goaaats/FFXIVQuickLauncher/wiki/Setting-up-OTP-Phone-Shortcuts#android-versions-after-10) doesn't require root and fixes the issue. (Thanks again, Catalysta#8888!)
