### ISSUE TITLE
Not autologin

### ISSUE THREAD

**Issue by Mara-Li** [goaaats/FFXIVQuickLauncher#136]
Since the last update, the launcher wipe my informations for connexion and not autologin. 

Happy new year of bug, Goaat ! x)

**Comment by Dinokin** [comment]
can confirm. autologin not working for me.

**Comment by werewolfboy13** [comment]
same issue here

**Comment by Aida-Enna** [comment]
Solved in pull #137, closing. Thank you for reporting!
