### ISSUE TITLE
launcherConfig.json does not exist, creating new...

### ISSUE THREAD

**Issue by cheers12** [goaaats/FFXIVQuickLauncher#139]
just installed 4.6 and it crashes without any error messages, only a Windows warning sound. I see this lines in the logs

2020-01-02 21:53:17.270 -08:00 [INF] XIVLauncher started as xivlauncher-4.6.0.0-cc7e5ba
2020-01-02 21:53:17.324 -08:00 [INF] Loaded UI theme resource.
2020-01-02 21:53:17.326 -08:00 [INF] Loading MainWindow for account ''
2020-01-02 21:53:17.329 -08:00 [INF] LauncherSettings at C:\Users\<removed>\AppData\Roaming\XIVLauncher\launcherConfig.json does not exist, creating new...

**Comment by goaaats** [comment]
Hey! Can you please open your event viewer, go to application logs and show me the last events for XIVLauncher.exe?

**Comment by cheers12** [comment]
Faulting application name: XIVLauncher.exe, version: 4.6.0.0, time stamp: 0xf3c4963b
Faulting module name: d3d9.dll, version: 10.0.18362.387, time stamp: 0xc808fce5
Exception code: 0xc0000005
Fault offset: 0x00000000000ac44e
Faulting process id: 0xde4
Faulting application start time: 0x01d5c1f717b1df5d
Faulting application path: C:\Users\<removed>\AppData\Local\XIVLauncher\app-4.6.0\XIVLauncher.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 7685ecbe-b470-44ff-8515-0f17af6d647d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by goaaats** [comment]
There should be another event above or below with more information, it's split up sadly - could you take another look?

**Comment by cheers12** [comment]
Fault bucket 1634928301043050222, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: XIVLauncher.exe
P2: 4.6.0.0
P3: f3c4963b
P4: d3d9.dll
P5: 10.0.18362.387
P6: c808fce5
P7: c0000005
P8: 00000000000ac44e
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC98B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB03.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB13.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB21.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB32.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_XIVLauncher.exe_5153d2eae2853c76c5beb8497a3febb49551636_02eaf7e6_1fd2597c-bd02-4db2-8079-1fc72ffbfff5

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3e667a51-8b3c-4cc5-8ea1-14095433da51
Report Status: 268435456
Hashed bucket: cfba38bee12ceaebc6b06ea0a8e766ee
Cab Guid: 0

**Comment by Aida-Enna** [comment]
@cheers12 Heya! Is this still an issue?

**Comment by Aida-Enna** [comment]
Assuming fixed due to lack of activity - Please open a new issue if this is not the case. Thank you!
