### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by gucciBane** [goaaats/FFXIVQuickLauncher#142]
Hey,

I had my bot set up correctly and it was working fine until an update a few months back. I've tried updating the ID just in case, but it hasn't fixed it.

**Comment by Aida-Enna** [comment]
@gucciBane Are you still having issues with it?

**Comment by gucciBane** [comment]
Yeah, unfortunately I never figured it out.

**Comment by Aida-Enna** [comment]
Try following [this new guide](https://github.com/goaaats/FFXIVQuickLauncher/wiki/How-to-set-up-a-discord-bot) from the beginning (or from linking it to XIVLauncher if your bot works with something else already) and see if that fixes it.

**Comment by Aida-Enna** [comment]
Gonna close this for now since it's not an XIVLauncher issue - feel free to join the discord and we'll help out with the bot stuff, though! https://discord.gg/aSuNjps
