### ISSUE TITLE
Launcher provides no way to set the discord notification channel for /xlbonus

### ISSUE THREAD

**Issue by ff-meli** [goaaats/FFXIVQuickLauncher#143]
It looks like this was never added to the UI - the DiscordFeatureConfiguration that is copied from Dalamud into the launcher is old and doesn't have the field at all (CfPreferredRoleChannel), and nothing is in place to configure it from the user end.

So the user experience is that using the command in game will work, but will also always report a warning that there is no discord channel configured; but there is also no way to configure the channel without directly editing the configuration json.

(Maybe at the same time, the Fate notification stuff could be removed, or at least hidden)

**Comment by goaaats** [comment]
This is done in https://github.com/goaaats/FFXIVQuickLauncher/commit/6e8b24cc0f0b6241f946f640c931012e5540f1b4

**Comment by ff-meli** [comment]
This is still broken, but in a different way.  It looks like there is a copy/paste bug in the xaml now, so df notify and bonus notify clash
```
<Button x:Uid="Button_4" Margin="0,7,0,10" HorizontalAlignment="Center" VerticalAlignment="Bottom" Click="SetDutyFinderNotificationChannel_OnClick" ToolTip="Set the Duty Finder notification channel.">Set Duty Finder notification channel</Button>
<Button x:Uid="Button_4" Margin="0,0,0,10" HorizontalAlignment="Center" VerticalAlignment="Bottom" Click="SetDutyFinderNotificationChannel_OnClick" ToolTip="Set the Roulette Bonus notification channel.">Set Roulette Bonus notification channel</Button>
```
