### ISSUE TITLE
Sync characters' setting wrong after create a new character

### ISSUE THREAD

**Issue by maiko-tan-coding** [goaaats/FFXIVQuickLauncher#148]
As below, when I enabled `Synchronize Character Data` and create a new character, whether log in the main character or not, it will cause the new character's setting to overwrite the main one.
After learning your code, I find out that you compare the last modified time of the file `ADDON.dat` (what I know was that it saved the HUD layout settings) , to ensure which the main character is.
Could you offer a setting to input the name of the main character? So that we can manually determine which the main character is.

**Comment by Aida-Enna** [comment]
The way the option works is that you keep it off until you make a new character, then turn it on and log into your main to sync your main to everything, then turn it back off again.

The concern with character names is that you could have multiple ones with the same name and different worlds - There are ways to work around that I suppose and would require some testing but at the moment there are no intentions on changing how this works. Sorry!
