### ISSUE TITLE
Crash though antivirus is setup

### ISSUE THREAD

**Issue by Seolenn** [goaaats/FFXIVQuickLauncher#150]
Whenever I launch it, it crash when i click on anything of the window.
Did i miss something ?

**Comment by Aida-Enna** [comment]
@Seolenn Is this still an issue?

**Comment by Seolenn** [comment]
I've just 1 min ago re-downloaded it and now it seems to work perfectly ! don't know if anything changed but i'm happy though :D

**Comment by Aida-Enna** [comment]
Awesome, thanks for responding! \ o /
