### ISSUE TITLE
Apps not getting added to Auto-Launch

### ISSUE THREAD

**Issue by dustin-lennon** [goaaats/FFXIVQuickLauncher#164]
**Describe the bug here:**
When adding new applications to the auto launch list, they are not getting added.

**Steps to reproduce the bug:**
1. Click on Settings
2. Click on Auto-Launch
3. Add new application (i.e, ACT or TeamCraft)
4. Application does not get added to list after save

**Expected behavior**
Applications get added to the auto launch list after adding.

**Screenshots**
![Annotation 2020-02-21 230024](https://user-images.githubusercontent.com/92093/75086082-06290780-54fe-11ea-95bd-ee626feda51d.png)

![Annotation 2020-02-21 230302](https://user-images.githubusercontent.com/92093/75086104-5acc8280-54fe-11ea-9426-cfa34e8ac9fd.png)

**Other information (*please* complete the following information):**
  Operating System:
  XIVLauncher version: 4.7 - Pre Release
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Trying to add ACT to run as Admin & TeamCraft

**Additional information**

`launcherConfigV3.json`

```
{
  "AdditionalLaunchArgs": "",
  "AutologinEnabled": "false",
  "CharacterSyncEnabled": "false",
  "GamePath": "E:\\Games\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn",
  "InGameAddonEnabled": "true",
  "SteamIntegrationEnabled": "false",
  "IsDx11": "true",
  "Language": "English",
  "UniqueIdCacheEnabled": "false",
  "AddonList": "[{\"$type\":\"XIVLauncher.Addon.AddonEntry, XIVLauncher\",\"IsEnabled\":true,\"Addon\":{\"$type\":\"XIVLauncher.Addon.RichPresenceAddon, XIVLauncher\",\"Name\":\"FFXIV Discord Rich Presence\"}}]"
}
```

**Comment by ninaarens** [comment]
I can replicate this. However, when you close and open the launcher settings, the application you added will be there. So it seems to just be a display issue. Hope that helps.

**Comment by dustin-lennon** [comment]
I have closed and reopened the launcher many times and they are never
there.

**Comment by Zyian** [comment]
Debugging this a little: Found that
https://github.com/goaaats/FFXIVQuickLauncher/blob/master/XIVLauncher/Windows/SettingsWindow.xaml.cs#L156
When the addon goes to get appended to the addonlist, the Add() fails leaving only the original list in its place

**Comment by goaaats** [comment]
This is fixed in https://github.com/goaaats/FFXIVQuickLauncher/commit/d6b587da3e02a7a533b146003a277527613c6ecc
