### ISSUE TITLE
New version breaks shortcuts

### ISSUE THREAD

**Issue by rsigim** [goaaats/FFXIVQuickLauncher#173]
![exemple](https://user-images.githubusercontent.com/22231296/75458509-aa76d800-595c-11ea-9f26-77d6bd42b553.png)

I mainly got this problem by using 2-3 accounts on shortcuts,
and every time we got a new version, the path on the shortcuts leads to the old version folder.
If possible to the .exe be on root folder or without the version on folder name kinda solves the problem.

**Comment by goaaats** [comment]
This is fixed in source for 4.8.1.0
