### ISSUE TITLE
Error code is happening when trying to Launch, after fix in changelog

### ISSUE THREAD

**Issue by Thregenbeck** [goaaats/FFXIVQuickLauncher#174]
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 246
4.7.3.0
a55b6fb
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True

[]

Shown when launching game, tried to remove all traces of every xivlauncher to no avail.

**Comment by goaaats** [comment]
Hi, thanks for reporting. The next version will have some more logging information so I can see what's going on, sorry.
In the meantime, can you try to disable your antivirus? This is on Windows 10?

**Comment by Thregenbeck** [comment]
I think I figured this out as soon as I posted it. I changed my file directory from G:\Final Fantasy\SquareEnix\FINAL FANTASY XIV - A Realm Reborn to G:\SquareEnix\Finalfantasyxiv and it works, I was testing to see if it either did not like spaces or the - when converting it into a string and it works fine now. Hopefully that helps solve the issue

**Comment by stmikaine** [comment]
still persists for me even after i changed the folder name :( same issue !

**Comment by Thregenbeck** [comment]
Yeah I completely reinstalled my game after, I feel like theres either changed files from previous installs or another 3rd party addon, like reshade or textools that could be messing with it, pure speculation though, if you're that desperate you can completely redownload the game and it should work.

**Comment by stmikaine** [comment]
probably that actually-- ill give it some shots

**Comment by Aida-Enna** [comment]
@stmikaine Did redownloading the game fix it?

**Comment by stmikaine** [comment]
@Aida-Enna it did!  i figured an outdated mod was probably doing the trick

**Comment by Aida-Enna** [comment]
Weird! Thanks for responding! \ o /
