### ISSUE TITLE
Suggestion: Button to open plugin directory

### ISSUE THREAD

**Issue by takhlaq** [goaaats/FFXIVQuickLauncher#175]
**What is your suggestion/feature request?**
A cweaw and concise descwiption of what the pwobwem is. Exampwe: ``Thewe awe nyo goats in the waunchew.``

**Describe how you'd like this to work**
A cweaw and concise descwiption of what you want to happen. Exampwe: ``I want the nyew icon fow the waunchew to be a goat and awso thwow in some "baaaahs" in the text.``

**Additional context**
something that'll open (or show and open) plugins dir in regular explorer window
maybe even a zip file to drag to the launcher under plugins tab or something to extract/install plugin to appropriate dir (like zip flashy things)

**Comment by Aida-Enna** [comment]
Added with https://github.com/goaaats/FFXIVQuickLauncher/commit/be9c8de8934398065b541ff60ce1901ed6fe890f, which was *supposed* to be a PR. My bad!
