### ISSUE TITLE
Detect new patch to download.

### ISSUE THREAD

**Issue by sslesar** [goaaats/FFXIVQuickLauncher#18]
Could you make a small pop up to know about download any new patches/updates in the official launcher? Thanks

**Comment by goaaats** [comment]
Technically, it shouldn't let you log in if an update is pending - is this not the case? I think that worked for me on the last hotfix

**Comment by sslesar** [comment]
![image](https://user-images.githubusercontent.com/25612653/56883481-b81eb100-6a5e-11e9-8ac5-dd5d53192557.png)
Just your launcher updated without problem but in game, I have not seen any updates from official FFXIV in EU.

**Comment by sslesar** [comment]
![image](https://user-images.githubusercontent.com/25612653/57985400-4afbab80-7a5f-11e9-99ad-1fc84c75592f.png)
Yes, solved!
