### ISSUE TITLE
Could not start the game correctly. Please report this error.

### ISSUE THREAD

**Issue by Crescr** [goaaats/FFXIVQuickLauncher#187]
**Describe the bug here:**
Error of the title as I get at the start of the game.
If you close the dialog with the OK button, the game itself will start normally.
However, the process of "NativeLauncher.exe" and "XIVLauncher.exe" continues even if the game ends.

**Steps to reproduce the bug:**
Just use this launcher as usual.

**Screenshots**
Example:
Error: (https://i.imgur.com/VBv20MS.jpg)
Process remains: (https://i.imgur.com/iyzYlYr.jpg)

**Other information (*please* complete the following information):**
  Operating System: Windows10 19041.153
  XIVLauncher version: 4.7.3
  Launching as admin?: UAC OFF(All admin)
  Using Steam?: No
  Addons/Plugins enabled: Discord Rich ON / In-Game in All OFF

**Additional information**
Error will disappear by pressing the OK, the process remains will not address at the end manually.
However, because it takes time and effort every time, you'd like a fix.

**Comment by goaaats** [comment]
Are you using MacType?

**Comment by Crescr** [comment]
> Are you using MacType?

Yes.
The following exclusions are set.
Launching directly using "ffxivlauncher64.exe" has no problem.
It is running with DX11 settings.
------------------------
ffxiv_dx11.exe
ffxivlauncher64.exe
ffxivboot64.exe
------------------------

**Comment by Aida-Enna** [comment]
You'll need to set an exception for the launcher too

**Comment by Crescr** [comment]
> You'll need to set an exception for the launcher too

Setting launcher exclusions resolved both issues.
I'm sorry, thank you.

**Comment by Aida-Enna** [comment]
No worries, glad it all worked out! Enjoy!
