### ISSUE TITLE
Input Box glitch on Windows 7 

### ISSUE THREAD

**Issue by altissia86** [goaaats/FFXIVQuickLauncher#19]
![image](https://user-images.githubusercontent.com/43957601/56195142-89680a00-605e-11e9-9baf-0c1b0cb14037.png)

I know Windows 7 will be dead soon, but I still use and love this OS. I understand if you dont want to support it. I just want to let you know about this glitch.

**Comment by goaaats** [comment]
Can you use the boxes normally? I don't have any way to test Windows 7, so if it doesn't impact functionality, I don't think I can do anything about it.

**Comment by altissia86** [comment]
no, i cant. i copy paste and check remember user name and password :D

**Comment by Mortalitas** [comment]
Just submitted a pull request that should fix this. For some reason Windows 7 seems to need the text inputs to be 1px taller.

**Comment by goaaats** [comment]
Fixed by https://github.com/goaaats/FFXIVQuickLauncher/pull/30 - thank you!
