### ISSUE TITLE
App would be still running at the background while it checks for update failed

### ISSUE THREAD

**Issue by maiko-tan-coding** [goaaats/FFXIVQuickLauncher#194]
**Describe the bug here:**
App would be still running at the background while it checks for update failed.

**Steps to reproduce the bug:**
1 run XivLauncher.exe
2 it would access the update site ( I noticed it was `api.github.com`, which was inaccessible sometimes because of the disturb from the firewall.)
3 then I got a prompt said it connect to the update site failed.
4 click OK, the prompt would disappear, but the application was still run at the background.
5 if I repeat steps `1~4`, there would be much more instances of the application running.

**Expected**
any method of below:
1 even failed in checking for update, the main window would show up.
2 prompt error while connection failed, click OK, then it exits completely.

**Other information**
  Operating System: Windows 10 Pro (1909 OS Build 18363.720)
  XIVLauncher version: 4.7.3.0
  Launching as admin?: No
  Using Steam?: Not steam account but steam runs background.
  Addons/Plugins enabled: `Discord Rich Presence`

**Comment by goaaats** [comment]
In 4.8.1.0 this will kill the app. If you need to run without updates, you can download a GitHub artifact or build yourself with the XL_NOAUTOUPDATE flag set.
