### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by chernobog** [goaaats/FFXIVQuickLauncher#20]
Please add the option to change the launcher to dark mode or follow Windows 10 app mode setting (ms-settings:colors).

**Comment by goaaats** [comment]
Added in https://github.com/goaaats/FFXIVQuickLauncher/commit/bc98324de08311c30a21cc64960909a94bb5c412, will be in the next update together with the addon stuff

**Comment by kjiempreecha** [comment]
If possible, can you add a manual toggle for the dark mode within the launcher itself? I don't like to use the Windows dark mode because a lot of the native apps look terrible.

**Comment by forteddyt** [comment]
I would also like a feature like this 😄
