### ISSUE TITLE
New icon is invisible on Windows 10 Dark Mode

### ISSUE THREAD

**Issue by pigsflew** [goaaats/FFXIVQuickLauncher#204]
the new icon is lovely but unfortunately it's basically invisible if Windows is in dark mode or you have a complex background.

![Start Bar](https://user-images.githubusercontent.com/868821/78006967-82c7b680-72f2-11ea-9d40-3c216c86422c.png)
![Complex Background](https://user-images.githubusercontent.com/868821/78007602-5e200e80-72f3-11ea-80d8-42aa6eae7142.png)
![Folder small](https://user-images.githubusercontent.com/868821/78007102-a8ed5680-72f2-11ea-8a32-c9958f506b08.png)
![Folder large](https://user-images.githubusercontent.com/868821/78007145-b60a4580-72f2-11ea-8396-62c52b13033c.png)

A minor tweak to improve this would be to apply a glow effect to the artwork's edges, and smaller cropped versions of the icon for smaller scales.

![Complex Background](https://user-images.githubusercontent.com/868821/78007670-73953880-72f3-11ea-855e-9cbbbe537f4c.png)
![Folder Large](https://user-images.githubusercontent.com/868821/78007320-02558580-72f3-11ea-9d04-e9cd4c37e437.png)
![Folder Medium](https://user-images.githubusercontent.com/868821/78007471-2fa23380-72f3-11ea-9056-15a273d1dcdf.png)
![Folder Small](https://user-images.githubusercontent.com/868821/78007520-4183d680-72f3-11ea-8cb0-1b81423e5f99.png)

[Zip file of all the sizes & the resulting ico file.](https://github.com/goaaats/FFXIVQuickLauncher/files/4407826/xivlauncher-glow.zip)

FWIW, i used the gimp with "drop shadow" but a bright color tinted slightly gold, the sharpen tool; at 256x256 I cropped to 196x196 and then resized down from there; at 48x48 i cropped to 32x32.

To make the resulting ico file I used [the RedKetchup icon editor](https://redketchup.io/icon-editor).

**Comment by goaaats** [comment]
Thanks for the proposal! That looks great, tho I'd probably go for white or red glow instead.
I'll play around with it in a bit :)

**Comment by goaaats** [comment]
Feel like this is fine now!
