### ISSUE TITLE
QuickLauncher doesn't start after update

### ISSUE THREAD

**Issue by Vitoire** [goaaats/FFXIVQuickLauncher#22]
Hi! 

After the latest update, my QuickLauncher refuses to start at all. Tried removing it, redownloaded it, still the same issue. Tried to start in Administrator mode as well. Had a quick look in Task Manager, only WerFault.exe starts and then immediately quits after being up for not even a second. 

Any ideas how I can fix this issue?

**Comment by goaaats** [comment]
Are you running Windows 7? If no, which Windows 10 version?

**Comment by Vitoire** [comment]
Windows 7 Professional 64-bit

**Comment by goaaats** [comment]
Can you try this build? Should work with this one.
[XIVLauncher.zip](https://github.com/goaaats/FFXIVQuickLauncher/files/3101045/XIVLauncher.zip)

**Comment by Vitoire** [comment]
Yup, worked! Thank you so much!

**Comment by goaaats** [comment]
Alright, I fixed this in https://github.com/goaaats/FFXIVQuickLauncher/commit/4945bf4f22838311356964bc40c37ea904d55711, was an oversight on my part - sadly, this means everyone on Windows 7 has to update manually. I've taken some precautions that this won't happen again.
