### ISSUE TITLE
Need to enter OTP after using maintenance queue

### ISSUE THREAD

**Issue by KazukiMutou** [goaaats/FFXIVQuickLauncher#24]
Currently, on the official launcher you're able to log in (and update, if available) when the servers are down. You can stay logged in for a couple of hours, and then just hit the play button when the servers come up without having to re-log.

On your launcher, I'm asked to enter the OTP _after_ the maintenance queue sees that the servers are up. So it's just sitting there waiting for input.

tldr:

Currently:
1. Click maintenance queue button
2. Maintenance queue waits until servers come up
3. When servers come up, asks for OTP, then launches game.

Expected:
1. Click maintenance queue button
2. Be asked for OTP
3. Maintenance queue waits until servers come up, launches game with given credentials.

**Comment by Aida-Enna** [comment]
Under **Settings** -> **About**, checkmark the **Enable experimental UID cache**. As noted in #11, you'll need to relogin in about once every 3 days or so, so keep that in mind.

**Comment by Jessidhia** [comment]
This could be implemented as a "single session" cache instead of the whole experimental cache thing; this way, cache eviction happens when either the launcher... launches or you close the launcher, avoiding the whole problem with manual eviction. 🤔
