### ISSUE TITLE
OTP pop-up doesn't grab focus on auto-login

### ISSUE THREAD

**Issue by dude22072** [goaaats/FFXIVQuickLauncher#25]
When auto-login is enabled with OTP the window doesn't grab keyboard focus on launch despite the window appearing on top of everything else and the cursor flashing.

**Comment by Outfenneced** [comment]
I was going to try to create a fix for this earlier today, but I can't personally reproduce this issue on v1.5. 

I can type immediately into the OTP box once the application launches without clicking the box as long as I haven't clicked somewhere else, but that puts the whole window in the background anyway. Once in a while it manages to become unselected somehow (can't even click off it normally from what I can tell), but I haven't been able to reproduce an instance where it appears selected but is actually not focused.

**Comment by Aida-Enna** [comment]
Not reproducible/fixed in the latest version. If this is still an issue, please comment here or open a new issue. Thank you!
