### ISSUE TITLE
Opening launcher shows huge error.

### ISSUE THREAD

**Issue by NLDGreen** [goaaats/FFXIVQuickLauncher#26]
![image](https://user-images.githubusercontent.com/36112617/56870481-e6a87780-69dd-11e9-9afd-de1412b55da2.png)

**Comment by chernobog** [comment]
I am receiving this after deleting the config file from the same directory as the exe. I had been attempting to wipe out my configs after having chosen to save my password and auto-login. Now I get this even after deleting all files from the directory, downloading a new copy of the exe and running it.

**Comment by chernobog** [comment]
Changing the name of the parent directory appears to resolve the issue.

**Comment by goaaats** [comment]
This seems to be an issue with upgrading settings - I got samples to try and troubleshoot, the best way to fix it at this time is to either delete the XIVLauncher folders in %AppData% or move it to another directory, as you said.

**Comment by goaaats** [comment]
I figured out where this one came from and improved my process, so it should not happen again - closing this, please report again if it reappears.
