### ISSUE TITLE
Multiboxing + multiple accounts

### ISSUE THREAD

**Issue by goaaats** [goaaats/FFXIVQuickLauncher#28]
- [x] Hack around Square Enix multiboxing prevention
- [x] Add UI to store multiple account logins

**Comment by EvilMeow** [comment]
@goaaats Any update on this possibly being finished anytime soon? I would really love to run more than 2 instances of the game for bard playing.

**Comment by goaaats** [comment]
That's already finished actually! I was just waiting on publishing a new version, but I guess I will upload it today.

**Comment by EvilMeow** [comment]
That's wonderful news. I can't wait to test it out!

**Comment by goaaats** [comment]
Try this one, should be working: https://github.com/goaaats/FFXIVQuickLauncher/releases/tag/1.6

**Comment by EvilMeow** [comment]
Using 1.6, I don't seem to be able to login with a 3rd client. The launcher stops responding and then eventually closes itself without a third instance opening.

**Comment by goaaats** [comment]
Did you start all of them with XIVLauncher? It will only work if you do that - I've just tried again, seems to work fine for me. If it keeps happening, can you dm me on discord so we can troubleshoot(meeboo#3048)?

**Comment by EvilMeow** [comment]
I did launch them all with XIVLauncher. I'll send you a message on discord for troubleshooting.

**Comment by KariArisu** [comment]
Any progress on being able to store multiple accounts? I have access to a few different accounts, and it would be nice to just have a couple buttons I could use to login to different ones without re-typing information each time.

**Comment by goaaats** [comment]
Before 5.0, probably

**Comment by KariArisu** [comment]
Sounds good. Even if it's ugly as sin I just want the functionality lol

**Comment by LyraMeow** [comment]
@goaaats The multi-box login seems to be broken at the moment with v3.6. I'm not able to start more than 2 clients at once.

* Start launcher 
* Sign into account 1
* Game starts
* Start launcher
* Sign into account 2
* Game starts
* Start launcher
* Sign into account 3
* Error, game doesn't start.

Error log.
```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, Boolean closeMutants) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 211
3.6.0.0
3051009
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English


[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": false,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]
```

---

I also noticed the multi-account user UI can't be scrolled to display more than 8 account. 


![link](https://i.imgur.com/2cX5pOr.png)

**Comment by goaaats** [comment]
Noted - honestly the thought of someone using more than 8 accounts never came to my mind

**Comment by mibby** [comment]
I'm sure, it's pretty unusual. I use multiple accounts for bard performance though.

**Comment by LyraMeow** [comment]
I'm sure, it's pretty unusual. I use multiple accounts for bard performance though.

**Comment by Aida-Enna** [comment]
@LyraMeow Is the 8 account limit still an issue?

**Comment by Aida-Enna** [comment]
Moved the 8 account limit to it's own issue, closing this issue.
