### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by dezwaan** [goaaats/FFXIVQuickLauncher#3]
Really love this. Is there a way to have it queue to auto-login after maintenance? I can create a script to ping the servers, see when they're up, then get a notification to run this but I was wondering if it's possible to integrate that into this in order to login immediately after maintenance?

**Comment by goaaats** [comment]
Sure, I'll take a look if you can give me the info I need to fetch maintenance status

**Comment by goaaats** [comment]
Never mind
https://github.com/goaaats/FFXIVQuickLauncher/commit/f040b2cf428486596afdc57f67a559e9caf41de9
This is kinda bad but it works, don't have the time to make it beautiful right now, maybe after 4.1
