### ISSUE TITLE
Icon that is not copyright infringement

### ISSUE THREAD

**Issue by goaaats** [goaaats/FFXIVQuickLauncher#31]
Having an icon that isn't the game's logo or something straight out of the game would be nice - maybe still inspired by dalamud. I could probably need help with this so if anyone even reads this and wants to give it a shot, go ahead! Thanks!

Needs to be 512x512 at a minimum.

**Comment by zuurw** [comment]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by InkyQuill** [comment]
Maybe something like this?
![dalamud](https://user-images.githubusercontent.com/16044715/67140894-834e2280-f267-11e9-9560-e58c11600b89.png)

Does it look dalamudish and allaganish? Am I on the right track, what do you think? It's not finished, but I wanted to hear some thoughts of others.

**Comment by InkyQuill** [comment]
Also, as an icon, I think we can make it evolving
- 16×16 is just red flames around a black circle that is Dalamud
![dl16](https://user-images.githubusercontent.com/16044715/67142850-01adc300-f26e-11e9-9f9e-3f07fc2bdf25.png)
- 32×32 is red and light-red flames
![dl32](https://user-images.githubusercontent.com/16044715/67142855-0bcfc180-f26e-11e9-85e5-777ad0a66940.png)
- 64×64 is full flames with a little cracks
![dl64](https://user-images.githubusercontent.com/16044715/67142860-14c09300-f26e-11e9-91d4-a8836ab47fff.png)
- 96×96 is the image above
![dl128](https://user-images.githubusercontent.com/16044715/67142864-1e49fb00-f26e-11e9-8be4-d2be1f776340.png)
- 128×128+ has stylized wings of Bahamut or something like that.

Well, still needs work.

**Comment by gucciBane** [comment]
I have a few unused pieces that I had made for a server too that could be adjusted.
![twitter](https://user-images.githubusercontent.com/49180180/77041193-160dfd00-697f-11ea-9f23-88c6f298721c.png)
![logo](https://user-images.githubusercontent.com/49180180/77041182-0bebfe80-697f-11ea-9c32-a74cd5e5338b.png)

**Comment by goaaats** [comment]
Hey @gucciBane, that looks awesome - hope this is not too much to ask, could you maybe send me a PSD or transparent version of your proposals?
Thanks a lot! I'm goat#3048 on discord.

**Comment by gucciBane** [comment]
No probs. Here are some pngs, lemme know if they're not big enough or whatever and I'll format some AIs.
![echoLogo2](https://user-images.githubusercontent.com/49180180/77240428-36ba9a80-6bab-11ea-8f50-f7d6431d33ea.png)
![echoLogo1](https://user-images.githubusercontent.com/49180180/77240429-37533100-6bab-11ea-9ad6-69c99e0bc4f9.png)

**Comment by goaaats** [comment]
Thanks a lot! Added you to the credits :)
We're gonna use the latter one with a different color in XL and the red one in Dalamud, if that's fine by you.

**Comment by goaaats** [comment]
Got this in both Dalamud and XIVLauncher!

**Comment by gucciBane** [comment]
Oh, yeah, woops. Didn't see that notification. No problem!

**Comment by KazWolfe** [comment]
@gucciBane Hiya, would it be possible for me to request an SVG of the latter meteor logo if you still have it? Would come in handy for a couple things we're planning.

Thank you!

**Comment by gucciBane** [comment]
Sure, though if I remember right, the art is raster, so I'll have to convert it. I can see if I can fit it in this weekend.

**Comment by gucciBane** [comment]
Sorry, got busy! So you guys still need this?

**Comment by KazWolfe** [comment]
If you have time, it would still be much appreciated. Thank you!

**Comment by gucciBane** [comment]
Sure! Do you guys have need of an actual logo version? The art wasn't
initially made with small scaling in mind (ie Desktop icon) and might
benefit from some typography.

**Comment by KazWolfe** [comment]
An actual logo version wouldn't be bad, honestly. I'm not necessarily sure any typography would be necessary, but an optimized version would definitely be great. The vector version would still be the higher "need" though.

**Comment by gucciBane** [comment]
Cool. Here's an SVG - ![xivlauncher_Jun5](https://github.com/goatcorp/FFXIVQuickLauncher/assets/49180180/fb4cad03-31a5-4426-abac-d2b03db17e7e)

**Comment by KazWolfe** [comment]
Awesome, thank you for getting that over to us!
