### ISSUE TITLE
New chat filter addon side effect

### ISSUE THREAD

**Issue by Krojack** [goaaats/FFXIVQuickLauncher#35]
Side effect to enabling the newly added RMT chat filter is in-game chat notification sounds no longer work.  I turned off the new addon and my chat sounds started working again.

This isn't referring to the <se.#> sounds either.  These are the sounds under Character Config > Log Window Settings > Notification Sounds that can be set for chat channels.

![ffxiv_05312019_112055_943](https://user-images.githubusercontent.com/908461/58716158-66878000-8396-11e9-9bf6-048be0775f0f.jpg)

**Comment by goaaats** [comment]
Alright, thanks for reporting - I knew something was missing but I couldn't pin it down. Gonna check this out soon.

**Comment by goaaats** [comment]
This should be fixed, thanks again to Mino, just restart your game with XIVLauncher. Can you try?
