### ISSUE TITLE
Chat bug in Eureka

### ISSUE THREAD

**Issue by xryan45** [goaaats/FFXIVQuickLauncher#40]
All options except "Target" become unavailable while selecting a target through the chat window in Eureka when using the in-game chat features. When leaving Eureka the options come back. Not sure why this is only happening in Eureka! Thanks!

With features on:
![ffxiv_dx11_2019-06-06_14-27-50](https://user-images.githubusercontent.com/51463132/59067829-6d673480-8867-11e9-9e75-7e435c8eb51f.png)

With features off:
![ffxiv_dx11_2019-06-06_14-33-45](https://user-images.githubusercontent.com/51463132/59068088-1f066580-8868-11e9-9d01-9ec799f01f52.png)

**Comment by goaaats** [comment]
I'm getting told that this is normal in Eureka - supposed to happen without the addon too. Can you check with the official launcher?

**Comment by xryan45** [comment]
Both screenshots are from using the launcher but I've never encountered the bug with the official launcher. Results using the official launcher are the same as this one without chat features turned on:

![ffxiv_dx11_2019-06-07_15-35-01](https://user-images.githubusercontent.com/51463132/59137169-36625300-893b-11e9-9699-054111fa1e12.png)

**Comment by goaaats** [comment]
This was fixed by Meli in https://github.com/goaaats/Dalamud/pull/9, sorry for the delay!
