### ISSUE TITLE
Crashing after Login (OTP)

### ISSUE THREAD

**Issue by Neithis** [goaaats/FFXIVQuickLauncher#42]
After I enter my OTP the game starts but the OTP Windows stays up for a couple of seconds and then QuickLauncher crashes.

I have attached a picture of what it looks like.
![Screenshot_1](https://user-images.githubusercontent.com/30007060/59139862-39d2fa00-898e-11e9-9a90-71416236f233.png)

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!
