### ISSUE TITLE
Doesn't open the configuration

### ISSUE THREAD

**Issue by Mara-Li** [goaaats/FFXIVQuickLauncher#46]
Hello.
I'm with the autologin. When I start with administrator, it's open the gamen and not the configuration.
So... I change my password so I can't log in !

Can you help me ?

Thanks.

I'm with Windows 10.

**Comment by goaaats** [comment]
Try holding the shift button when clicking the launcher, that should allow you to change your settings!

**Comment by Mara-Li** [comment]
Thanks !!!
