### ISSUE TITLE
launch error after updating to 2.1

### ISSUE THREAD

**Issue by Nyaughty** [goaaats/FFXIVQuickLauncher#53]
Throws this little guy on launching (admin/normal launch) after the update.
The game launches normally (with previously saved credentials)
The launcher fails to display news etc then crashes with that message (while the game runs).

[error.txt](https://github.com/goaaats/FFXIVQuickLauncher/files/3332130/error.txt)

**Comment by goaaats** [comment]
This is most likely caused by your antivirus. What are you running?

**Comment by Nyaughty** [comment]
Nothing, no AV running passively, only default windows firewall, turned it off and yet the same.

**Comment by goaaats** [comment]
Can you check if you have write access to ``%AppData%\XIVLauncher\Hooks``?

**Comment by Nyaughty** [comment]
The path was actually \XIVLauncher\addons\Hooks
I have full rights to the folder and the files inside
Moving the Hooks folder one level up did not change the error I'm getting

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!
