### ISSUE TITLE
(Suggestion) Option for slimmed/no embed for chat relay

### ISSUE THREAD

**Issue by theabhishek2511** [goaaats/FFXIVQuickLauncher#55]
The current way of the relay handling chat messages posted to discord (using embeds) looks visually nice, but take up a lot of vertical space, which IMHO could be used to display more chat lines. The following chat log, for example, has only six short messages but still takes up vertical space equivalent to a whopping 24 lines of messages.

![image](https://user-images.githubusercontent.com/2082634/60264804-bad44000-9901-11e9-904b-067fa4c59513.png)

So I'd like to optionally suggest addition of a flag to either not use embed or use a slimmed down embed for at least the chat relay. Something similar to how chat is displayed in-game would be nice for a slim display.

**Comment by goaaats** [comment]
This was implemented https://github.com/goaaats/Dalamud/commit/b857506fd6b007742622941e055d2d28c53187e3, hope you stuck around, sorry for closing so late!
