### ISSUE TITLE
Downloads closed-source components

### ISSUE THREAD

**Issue by Poliwrath** [goaaats/FFXIVQuickLauncher#56]
Was just wondering why this launcher seems to download closed-source components from https://goaaats.github.io/ffxiv/tools/launcher/addons/Hooks/latest.zip and https://goaaats.github.io/ffxiv/tools/launcher/addons/RichPresence/latest.zip, and always checks for updates and downloads from https://goaaats.github.io/ffxiv/tools/launcher/xivlauncher-latest.zip
 😳

**Comment by goaaats** [comment]
``https://goaaats.github.io/ffxiv/tools/launcher/xivlauncher-latest.zip`` is just for the auto-updater, if you download it and compare hashes to releases, they should match up. The "About" page has the git hash of the published build after the version number if you want to see exactly which commit a release is based on.

``goaaats.github.io/ffxiv/tools/launcher/addons/RichPresence/latest.zip`` is for Rich Presence which is Open Source, you can find it [here](https://github.com/goaaats/FFXIVRichPresence).

``goaaats.github.io/ffxiv/tools/launcher/addons/Hooks/latest.zip`` is the only real closed-source part at the moment, I am working on changing this and agree that it is a problem, there are some issues I need to resolve first though.

I'm striving to be transparent with these things and every component of XIVLauncher is fully managed, so I can only recommend you to check them out using https://github.com/0xd4d/dnSpy or another decompiler which should basically let you see the source. Sadly code signing certificates are expensive, but it's something I considered.
If you have any recommendations, I'd love to hear about them.

**Comment by Poliwrath** [comment]
Thank you for being transparent.
