### ISSUE TITLE
security of the saved log-in credentials?

### ISSUE THREAD

**Issue by ghostkill3r** [goaaats/FFXIVQuickLauncher#59]
sorry for posting this, but i have a question about the security of the saved log-in credentials.
are they encrypted or plain text?
if they are encrypted, what is the method used, i don't ask for specifics as that would make it unsafe but... i just like to know if these(my) credentials are safely sitting on my HDD.

**Comment by goaaats** [comment]
They are stored in the windows credential database, so pretty much as secure as possible - really, if malware has access to your computer, you basically already lost. Even for software like chrome and others :/

More to read up on here: https://support.microsoft.com/en-us/help/4026814/windows-accessing-credential-manager

**Comment by ghostkill3r** [comment]
thank you for clarifying.

have a nice day, and thank you for this launcher :)
