### ISSUE TITLE
With XIVLauncher FFXIV wont auto switch audio input

### ISSUE THREAD

**Issue by altissia86** [goaaats/FFXIVQuickLauncher#61]
With ShB FFXIV now can automatically switch default input. We no longer need to restart the game, but if I launch FFXIV with XIVlauncher it wont switch. 

Intended behaviour (tested on windows 10)
1. Default input HDMI TV (headset is not plugged in yet)
2. Start XIV with original launcher
3. Plugin headset, it will mute the TV and stream audio through headset automatically, no need restart game

How to reproduce the bug
1. Default input HDMI TV (headset is not plugged in yet)
2. Start XIV with XIVLauncher
3. Plugin headset, it wont stream audio to headset, still on TV

edit : grammar
edit 2 : include os

**Comment by altissia86** [comment]
i get this bug after applying windows 7 compability detailed in this issue

https://github.com/goaaats/FFXIVQuickLauncher/issues/49

when i remove windows 7 compability, i dont get this audio switching bug. it seems i have to choose between addons and audio switching.

**Comment by goaaats** [comment]
I will look into both issues - sadly I have no windows 7 machine to test on. If you're on my discord, please ping me so we can try to troubleshoot it.

**Comment by altissia86** [comment]
both issues are on windows 10. it's clean installed recently. i'll ping you on discord tomorrow.

**Comment by altissia86** [comment]
both issues are fixed with 2.7.0.0 release. thank you.
