### ISSUE TITLE
Launcher does not connect to discord bot

### ISSUE THREAD

**Issue by hi00ih** [goaaats/FFXIVQuickLauncher#66]
I've entered in the token from the application page in the client but no chat, fate or any notifications get sent to either a user account or a server channel that I set it to. 
Using /xlbotjoin in-game produces The XIVLauncher discord bot was not set up correctly or could not connect to discord. Please check the settings and the FAQ.

**Comment by goaaats** [comment]
If you're still having this issue, please post dalamud.txt from ``%AppData%\XIVLauncher\addons\Hooks``

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!
