### ISSUE TITLE
Level restriction do not work, bug or wanted?

### ISSUE THREAD

**Issue by Sephiroth91** [goaaats/FFXIVQuickLauncher#7]
Hey,

I have tested your Launcher,  I have tried to down grad my account for oldschool feeling while playing FFXIV. I have started the game  with  Realm Reborn instead of Stormblood. Gamefunctions worked well. I could not create an aura, going to maps of Heavensward or Stormblood or doing quests from the extentions, as ist should be. The only thing, that does not work is the level restriction. I can get higher than 50 in ARR, Its important  for me that the level restriction work. I can grow up to 70 by using ARR Extention by game start. 

Can you do something there or is that not possible? 
Or it is possible that you can manipulated the client that I do not come over 50 by using ARR,
Or is it only serverside?

Best wishes

**Comment by goaaats** [comment]
I don't think this is possible sadly, since it's server side -  you'd have to use a trial account.
