### ISSUE TITLE
xlhelp command not recognized

### ISSUE THREAD

**Issue by sidewinder94** [goaaats/FFXIVQuickLauncher#70]
Hi,

Started using the launcher yesterday, I am pretty convinvec at the moment, but thereis one feature I can't seem to get working => The in game features.

The game always says that /xlhelp is an unrecognized command.

Launcher version 2.8.0.0 - 73d9d93
Using DX 11
Tried as myself and as admin
Filled a bot token

Game language is french if that has any effect.

Thanks for any help.

Output.log and dalamud.txt joined in case there is any information I couldn't see.
[dalamud.txt](https://github.com/goaaats/FFXIVQuickLauncher/files/3393875/dalamud.txt)
[output.log](https://github.com/goaaats/FFXIVQuickLauncher/files/3393876/output.log)

**Comment by Kumicoo** [comment]
Same problem. Youre not the only one. I dont know how to fix but im replying like this so the dev sees its probably not your fault only - im having the exact same issue. On english game language

**Comment by Akee210** [comment]
Same here. Steam integration works. Discord Rich Presence shows everything accurately _except_ the current location is always on "Default". As for the rest I'm having the same issues

**Comment by VincentGM** [comment]
The new update messed with the memory addresses, we'll need to wait for an update.

**Comment by goaaats** [comment]
Should be fixed now, sorry for the delay.
