### ISSUE TITLE
xl help not recognized command ingame

### ISSUE THREAD

**Issue by Kumicoo** [goaaats/FFXIVQuickLauncher#71]
Same problem. Youre not the only one. I dont know how to fix but im replying like this so the dev sees its probably not your fault only - im having the exact same issue. On english game language

**Comment by VincentGM** [comment]
The new update messed with memory addresses. So we'll need to wait for an update.

**Comment by Kumicoo** [comment]
Man i hope so. Been More than a week.

**Comment by goaaats** [comment]
This should be fixed now. Sorry for the delay.
