### ISSUE TITLE
Steam integration broken.

### ISSUE THREAD

**Issue by Kumicoo** [goaaats/FFXIVQuickLauncher#72]
Launcher steam integration does not work - i cant even set a new directory, the whole tab seems broken, no matter where i click all it does it toggle the box on and off, i cant choose another directory and overall steam integration just broken.

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!
