### ISSUE TITLE
DRP showing location as "default"

### ISSUE THREAD

**Issue by NordicSnow** [goaaats/FFXIVQuickLauncher#78]
[output.log](https://github.com/goaaats/FFXIVQuickLauncher/files/3464482/output.log)
![image](https://user-images.githubusercontent.com/33619302/62418330-f910fd80-b62b-11e9-852f-433eef8ca56c.png)

**Comment by Kumicoo** [comment]
This thing is dead

**Comment by goaaats** [comment]
It's not, but shitting on me for having a real life when the last commit is 20 days ago doesn't make it harder for me to prioritize sleeping

**Comment by DJScias** [comment]
@goaaats Take your time.

Most, sans a few bad apples, are just making issues because we want to inform you it's broken but it's not a "FIX IT NOW".

Take all the time you need for this.

**Comment by goaaats** [comment]
Should be fixed
