### ISSUE TITLE
Will not start anymore. Even with shift held or running as admin, even after clean reinstall.

### ISSUE THREAD

**Issue by JamieAzure** [goaaats/FFXIVQuickLauncher#79]
This is what I get in the logs after clicking to start the app.  I get two pulses of the wait cursor, then nothing.  Have wiped the config, have reintalled, have tried as admin, tried with shift held, nothing seems to get it started any more.

> 2019-08-10 20:53:47.751 +02:00 [INF] XIVLauncher started with version 2.9.0.0, commit 64278d4
> 2019-08-10 20:53:47.798 +02:00 [INF] Loaded UI theme resource.
> **2019-08-10 20:53:47.800 +02:00 [INF] Loading MainWindow for account ''**
> 2019-08-10 20:53:48.011 +02:00 [INF] Starting update check.
> 2019-08-10 20:53:48.205 +02:00 [INF] AutoUpdaterOnCheckForUpdateEvent called.
> 2019-08-10 20:53:48.206 +02:00 [INF] No update: 2.9.0.0
> 2019-08-10 20:53:49.361 +02:00 [INF] Engaging Autologin
> 2019-08-10 20:53:58.985 +02:00 [INF] XIVLauncher started with version 2.9.0.0, commit 64278d4
> 2019-08-10 20:53:59.030 +02:00 [INF] Loaded UI theme resource.
> 2019-08-10 20:53:59.032 +02:00 [INF] Loading MainWindow for account ''
> 2019-08-10 20:53:59.232 +02:00 [INF] Starting update check.
> 2019-08-10 20:53:59.330 +02:00 [INF] AutoUpdaterOnCheckForUpdateEvent called.
> 2019-08-10 20:53:59.332 +02:00 [INF] No update: 2.9.0.0

**Comment by JamieAzure** [comment]
So, is this project actually not supported anymore?  Is that what you are saying @Kumicoo ?

**Comment by goaaats** [comment]
Are you using a shortcut to start the launcher

**Comment by JamieAzure** [comment]
I had been, but after seeing your message I went into the folder and tried it directly on the XIVLauncher.exe and it still has the same issues as mentioned in the original post.

**Comment by mmaine** [comment]
While this didn't happen to me in 3.0, as of 3.1 I'm experiencing the same issue. Log only has one entry:

`2019-08-29 12:29:29.817 +03:00 [INF] XIVLauncher started with version 3.1.0.0, commit b2d3bc7`

**Comment by toastyc12** [comment]
Same problem here. I can't even downgrade back to 3.0, because it auto-updates and gives me no way to force it to not to.

**Comment by dakkidaze** [comment]
The same here, just updated to 3.1.0.0, doesn't open at all, looked for it in task manager and it quit automatically

**Comment by goaaats** [comment]
Sorry, mistake on my part - if you got this problem, please download 3.2 from GitHub. Will take care so it doesn't happen again.

**Comment by JamieAzure** [comment]
Same issue still, clean reinstall.  Using version 3.3 from here.  What info would you like from my system to help assist in the debuggin?

**Comment by goaaats** [comment]
This was related to an oversight in the update process, improved it so it should not happen again - might have also been related to various other issues related to RivaTuner and RGSS apps.
