### ISSUE TITLE
Function error

### ISSUE THREAD

**Issue by Sephiroth91** [goaaats/FFXIVQuickLauncher#8]
Hello,

Custom launcher does not work after patch 4.5 If I start it, I get directly an errror.

Best wishes

**Comment by beckyeeky** [comment]
Same here.

**Comment by joso33** [comment]
I'm getting same error as user beckyeeky 

`Logging in failed. Check your login information or try again,`

**Comment by goaaats** [comment]
Should be fixed now, thanks for reporting: https://github.com/goaaats/FFXIVQuickLauncher/releases/tag/Build-7
