### ISSUE TITLE
/xlhelp not working if the game language is set to French

### ISSUE THREAD

**Issue by KurtySuit** [goaaats/FFXIVQuickLauncher#80]
Game saying /xlhelp doesn't exist

It works when i switch my game in English

**Comment by goaaats** [comment]
Can you copy the error message from the chat log?

**Comment by KurtySuit** [comment]
[3:57] XIVLauncher in-game addon loaded.
[3:57] La commande texte “/xlhelp” n'existe pas.
output.log [output.log](https://github.com/goaaats/FFXIVQuickLauncher/files/3537763/output.log)

**Comment by kazounet** [comment]
Same here with the latest version:
```
[16:16] XIVLauncher in-game addon loaded.
[16:16] La commande texte “/xlhelp” n'existe pas
```
Works if I flip the launcher to english as well but I'd prefer playing in french :-)

**Comment by sidewinder94** [comment]
Just a note from another french player, it started to work since the last FFXIVQuickLauncher update.
Game is in french, the original launcher too.
You might want to give it another go.

**Comment by goaaats** [comment]
Yes, this should be fixed now, sorry for the trouble!
