### ISSUE TITLE
Can't reach the settings menu to change Steam integration

### ISSUE THREAD

**Issue by MrBlackCreep** [goaaats/FFXIVQuickLauncher#84]
I can't reach the settings menu to check Steam integration since the error message telling me to do so pops up and the launcher closes. Launching as admin does the same. Editing the value for SteamIntegration to True XIVLauncher.exe.config doesn't seem to do anything.

**Comment by goaaats** [comment]
Please hold shift while starting the launcher, that'll let you change settings.
