### ISSUE TITLE
Could not check for updates. Cannot open client

### ISSUE THREAD

**Issue by hlouzan** [goaaats/FFXIVQuickLauncher#85]
First launch XIVLauncher auto-updated to new version as of 29/08/2019 since there is also a new FFXIV version I had to launch normal client. Relaunch game through XIVLauncher and I have this error.

![image](https://user-images.githubusercontent.com/26860054/63934290-429e0e00-ca5b-11e9-9e02-438398cc3d08.png)

**Comment by goaaats** [comment]
Should be fixed now.

**Comment by hlouzan** [comment]
Like a charm, thanks.
