### ISSUE TITLE
xiv launcher error

### ISSUE THREAD

**Issue by almalgam** [goaaats/FFXIVQuickLauncher#86]
System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteam, String additionalArguments, Boolean closeMutants)
3.3.0.0
0066b77
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
False
False
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": false,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]

**Comment by Zyian** [comment]
In order to use the Discord Rich Presence feature you need to run the launcher as admin

**Comment by goaaats** [comment]
That shouldn't be the case, are you on Windows 10?

**Comment by goaaats** [comment]
This cannot happen anymore, closing issue
