### ISSUE TITLE
FFXIV Expansion

### ISSUE THREAD

**Issue by Sephiroth91** [goaaats/FFXIVQuickLauncher#87]
Hello, I had to use the launcher to start the game out of nostalgia as a realm reborn as I find the old title screen nicer. 
Unfortunately I notice that I can no longer select the expansion with the current version 
Can you change this again or set the start arguments which expansion starts ? If so, how?
I found a line in the launcher config where expansion is when I change the setting, I don't notice any changes.

**Comment by goaaats** [comment]
Sadly, this is no longer supported due to it creating incompatibilities with Square Enix servers. Maybe I will bring something like this back in the in-game addon at some point though.
