### ISSUE TITLE
Non-standard text in *asterisks* is hidden in chat with in-game features enabled

### ISSUE THREAD

**Issue by DAOWAce** [goaaats/FFXIVQuickLauncher#90]
When using anything that isn't just default typed text (like auto-translation things, item links, flags, etc.), the text is completely hidden.

I initially thought this was due to the RMT filter, but it happened when disabled and eventually I figured out what triggered it.

Bit of an issue, as if anyone has * * surrounding something that's linked, it won't show up in chat.

In addition there's just numerous bugs with in-game features turned on that results in the chat window having bizarre issues; like a big empty space (https://i.imgur.com/flZtzKd.png), the chat randomly scrolling rapidly to a certain spot yet acting like it's all the way scrolled down (very annoying when trying to scroll up to re-read something), and another niggling issue I can't remember.

I want to keep using the ingame features solely for the duty notification, as that would remove the need to use the DFAssist plugin (which slows ACT's loading down tremendously), but in the interim I'm gonna have to disable the ingame features because, well, the issues are more irritating than ACT starting slowly.

Otherwise, really nice features!

**Comment by goaaats** [comment]
We recently improved chat handling and should have fixed a lot of these issues. Please give it another try!

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!

**Comment by DAOWAce** [comment]
Oh, yes, none of the issues I reported seemed to have been a problem anymore as of the release from December.

Sorry I never reported back, and thank you for the updates.
