### ISSUE TITLE
Wrong port on the iOS shortcut

### ISSUE THREAD

**Issue by florianbauch** [goaaats/FFXIVQuickLauncher#91]
The instructions [on the wiki](https://github.com/goaaats/FFXIVQuickLauncher/wiki/How-to-set-up-phone-shortcutsi) for the shortcut on iOS suggests replacing the IP and the shortcut defaults Port 1050, while only port 4646 works.

**Comment by Zyian** [comment]
I updated the wiki to reference the new screenshots that were upload that include the correct ports. This can be resolved

https://github.com/goaaats/FFXIVQuickLauncher/wiki/Setting-up-OTP-Phone-Shortcuts#ios

**Comment by goaaats** [comment]
Thank you!
