### ISSUE TITLE
Retainer Sales reported wrong

### ISSUE THREAD

**Issue by SoeyKitten** [goaaats/FFXIVQuickLauncher#92]
When selling stacks of things, the amount isn't picked up correctly:

![Ingame Message](https://i.imgur.com/keX7CMT.png)

![Discord Message](https://i.imgur.com/owwxu5M.png)

I would have expected it to report "Sold 5". 

And as an added feature request: I also would've expected it to report how much I sold it for :3

**Comment by goaaats** [comment]
This should be fixed now.
