### ISSUE TITLE
launcher not opening

### ISSUE THREAD

**Issue by dakkidaze** [goaaats/FFXIVQuickLauncher#96]
'reinstalled' the whole thing(delete xivlauncher folders under appdata\roaming and appdata\local) and downloaded the newest version from github and it doesn't open either

output.log said this
```
2019-09-15 00:54:01.038 +08:00 [INF] XIVLauncher started as xivlauncher-3.6.0.0-3051009
2019-09-15 00:54:01.138 +08:00 [INF] Loaded UI theme resource.
2019-09-15 00:54:01.141 +08:00 [INF] Loading MainWindow for account ''
2019-09-15 00:54:01.425 +08:00 [INF] Starting update check.
2019-09-15 00:54:01.932 +08:00 [INF] AutoUpdaterOnCheckForUpdateEvent called.
2019-09-15 00:54:01.936 +08:00 [INF] No update: 3.6.0.0
```

**Comment by Onibus** [comment]
I had the same issue and found that despite an entry in my Firewall (Bitdefender), the toggle was turned "off". Add an exception to allow traffic to your firewall rule whether it's Windows or your AV solution.

**Comment by dakkidaze** [comment]
> I had the same issue and found that despite an entry in my Firewall (Bitdefender), the toggle was turned "off". Add an exception to allow traffic to your firewall rule whether it's Windows or your AV solution.

Thanks for your help, sadly still not working. I disabled my firewall and it didn't want to launch either.

**Comment by mmaine** [comment]
I posted on the previous bug report too, if you run RTSS (Rivatuner), disabling it helps.

**Comment by dakkidaze** [comment]
> I posted on the previous bug report too, if you run RTSS (Rivatuner), disabling it helps.

It worked! Thank you sir!

Looking forward to a solution that makes them works together tho :)

**Comment by dakkidaze** [comment]
OK today when I wanted to run something written in C#(textools) and it refused to start until I close RTSS.
I believe there is something wrong regarding RTSS(or maybe my OS), and I think there should be a line in README telling people to close RTSS if launcher refuses to start.

**Comment by pigsflew** [comment]
[Another report has this comment](https://github.com/goaaats/FFXIVQuickLauncher/issues/94#issuecomment-532384334) saying to clear RTSS' cache which may allow you to run both together again. If you could give it a try, I can provide a doc change MR to Goaaats highlighting this issue.

**Comment by goaaats** [comment]
This was related to an issue with RivaTuner, which should be fixed now as soon as you update it. Thanks everyone!
