### ISSUE TITLE
Support proxy socksifier programs

### ISSUE THREAD

**Issue by sokol-44** [goaaats/FFXIVQuickLauncher#98]
Sometimes is faster to run game thru some kind of proxy.
Beacause FFXIV dont have internal setting for proxy one have to use some kind of socksifier ie: [sockscap64](https://www.sockscap64.com/homepage/), [example](https://www.sockscap64.com/forums/topic/sockscap64-how-to-launch-program-from-script-or-command-line/)

It is posible to add that kind option of option?

**Comment by sokol-44** [comment]
For local proxy socks5 on port 8088 command line will be:
`SocksCap64.exe -i127.0.0.1 -p8088 -t5 -n1 -r"[FULL PATH]ffxiv_dx11.exe" -a"DEV.DataPathType=1 DEV.MaxEntitledExpansionID=3 DEV.TestSID=[UUID] DEV.UseSqPack=1 SYS.Region=3 language=1 ver=2019.08.21.0000.0000"`

**Comment by Aida-Enna** [comment]
Outside the scope of the program and not planned for support at this time. Sorry!
